test-guru/config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout }

  get 'sessions/new'
  get 'users/new'
  root to: 'tests#index'

  resources :tests, only: :index do
    resources :questions, shallow: true do
      resources :answers, shallow: true
    end
    member do
      post :start
    end
  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  namespace :admin do
    resources :tests do
      patch :update_inline, on: :member

      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end
    resources :gists
    resources :badges
  end

  resources 'contacts', only: %i[new create]

  resources :badges, only: :index
end

test-guru/app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
  scope :right_answer, -> { where(correct: true) }
  validates :body, presence: true
  validate :validate_answers_quantity, on: :create

  private

  def validate_answers_quantity
    return unless question.answers.count >= 4

    errors.add(:answer, message: "wrong quantity of answers!" )
  end
end

test-guru/app/controllers/admin/answers_controller.rb
class Admin::AnswersController < Admin::BaseController
  before_action :find_question, only: %i[new create destroy]
  before_action :set_answer, only: %i[show destroy]

  def show; end

  def new
    @answer = @question.answers.new
  end

  def create
    @answer = @question.answers.new(answer_params)

    if @answer.save
      redirect_to admin_tests_path(@question.test)
    else
      render :new
    end
  end

  def destroy
    @answer.destroy
    redirect_to admin_test_questions_path(@question)
  end

  private

  def find_question
    @question = Question.find(params[:question_id])
  end

  def set_answer
    @answer = Answer.find(params[:id])
  end

  def answer_params
    params.require(:answer).permit(:body, :correct)
  end
end

test-guru/app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :authenticate_user!
end

test-guru/app/views/admin/answers/_answer.html.erb
<li  style="line-height: 150%">
  <p class="mt-1"><%= answer.body %></p>
  <p class="mt-1"><%= link_to t('actions.show'), admin_answer_path(answer), class: 'btn btn-outline-secondary' %>
  <%= link_to t('actions.edit'), edit_admin_answer_path(answer), class: 'btn btn-outline-secondary'  %>
  <%= link_to t('actions.delete'),
              admin_answer_path(answer),
              method: :delete,
              data: {confirm: 'Are you sure?'}, class: 'btn btn-outline-secondary'  %></p>
</li>

test-guru/app/views/admin/answers/_form.html.erb
<%= form_with model: [:admin, @question, @answer], local: true do |form| %>
  <%= render 'shared/errors', resource: @answer %>

  <P>
    <%= form.label :body %><br>
    <%= form.text_area :body, id: :answer_body, rows: 7, cols: 60  %>
  </P>

  <P>
    <%= form.label :correct %>:
    <%= form.check_box :correct, id: :answer_correct %>
  </P>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

test-guru/app/views/admin/answers/edit.html.erb
<h2>Editing Answer</h2>

<p><%= @answer.question.body %></p>

<%= render 'form', answer: @answer %>
<%= link_to 'Back',  admin_question_path(@answer.question) %>

test-guru/app/views/admin/answers/new.html.erb
<h2>New Answer</h2>

<p><%= @question.body %></p>

<%= render 'form', answer: @answer %>
<%= link_to 'Back', admin_question_path(@question), class:'btn btn-outline-secondary' %>

test-guru/app/views/admin/answers/show.html.erb
<h2>Question</h2>

<p>
  <%= @answer.question.body %>
</p>

<p> <strong>Answer: </strong>
  <%= @answer.body %>
</p>

<p> <strong>Correct: </strong>
  <%= @answer.correct %>
</p>

<%= link_to t('actions.back'), admin_question_path(@answer.question), class: 'btn btn-outline-secondary' %>