test-guru/config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout }

  get 'sessions/new'
  get 'users/new'
  root to: 'tests#index'

  resources :tests, only: :index do
    resources :questions, shallow: true do
      resources :answers, shallow: true
    end
    member do
      post :start
    end
  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  namespace :admin do
    resources :tests do
      patch :update_inline, on: :member

      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end
    resources :gists
    resources :badges
  end

  resources 'contacts', only: %i[new create]

  resources :badges, only: :index
end

test-guru/app/models/admin.rb
class Admin < User
end

test-guru/app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
  scope :right_answer, -> { where(correct: true) }
  validates :body, presence: true
  validate :validate_answers_quantity, on: :create

  private

  def validate_answers_quantity
    return unless question.answers.count >= 4

    errors.add(:answer, message: "wrong quantity of answers!" )
  end
end

test-guru/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

test-guru/app/models/badge.rb
class Badge < ApplicationRecord
  has_and_belongs_to_many :users
  before_destroy { users.clear }
  has_and_belongs_to_many :test_passages
  before_destroy { test_passages.clear }
end

test-guru/app/models/category.rb
class Category < ApplicationRecord
  has_many :tests, dependent: :destroy

  default_scope { order(title: :asc) }
end

test-guru/app/models/contact.rb
class Contact < MailForm::Base
  attribute :name,      validate: true
  attribute :email,     validate: /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message
  attribute :nickname, captcha: true

  def headers
    {
      subject: "TestGuru contact's form",
      to: ENV['ADMIN_MAIL'],
      from: ENV['SENDERS_MAIL']
    }
  end
end

test-guru/app/models/gist.rb
class Gist < ApplicationRecord
end

test-guru/app/models/question.rb
class Question < ApplicationRecord
  belongs_to :test
  has_many :answers, dependent: :destroy
  has_many :gists, dependent: :destroy

  validates :body, presence: true
end

test-guru/app/models/test.rb
class Test < ApplicationRecord
  def self.sorted_by_category(category)
    by_category(category).order(title: :desc).pluck(:title)
  end

  belongs_to :category
  has_many :questions, dependent: :destroy
  has_many :test_passages, dependent: :destroy
  has_many :users, through: :test_passages, dependent: :destroy
  belongs_to :author, class_name: 'User'

  validates :title, presence: true,
                    uniqueness: { scope: :level, message: "title and level pair should be unique!" }
  validates :level, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  scope :easy, -> { where(level: 0..1) }
  scope :normal, -> { where(level: 2..4) }
  scope :hard, -> { where(level: 5..Float::INFINITY) }
  scope :by_category, ->(category) { joins(:category).where('categories.title = :category', category: category) }
  scope :by_level, ->(level) { where('level = :level', level: level) }
end

test-guru/app/models/test_passage.rb
class TestPassage < ApplicationRecord
  belongs_to :user
  belongs_to :test
  belongs_to :current_question, class_name: 'Question', optional: true
  has_and_belongs_to_many :badges
  before_destroy { badges.clear }

  before_validation :before_validation_set_first_question, on: :create

  BOUNDARY_OF_SUCCESS = 85

  before_update do
    self.current_question = next_question
  end

  def accept!(answer_ids)
    self.correct_questions += 1 if correct_answer?(answer_ids)
    save!
  end

  def completed?
    current_question.nil?
  end

  def success?
    percentage_result < BOUNDARY_OF_SUCCESS
  end

  def percentage_result
    a = test.questions.count
    b = correct_questions
    (Float(b * 100) / a).ceil
  end

  def current_question_number
    test.questions.to_a.index(current_question) + 1
  end

  def all_questions
    test.questions.count
  end

  def progress
    Float(((current_question_number - 1) * 100) / all_questions).ceil
  end

  def end_time
    (created_at + (test.timer * 60)).to_s(:js_datetime)
  end

  def check_timer
    end_time < Time.now.to_s(:js_datetime)
  end

  private

  def before_validation_set_first_question
    self.current_question = test.questions.first if test.present?
  end

  def correct_answer?(answer_ids)
    return if answer_ids.nil?

    correct_answers.ids.sort == answer_ids.map(&:to_i).sort
  end

  def correct_answers
    current_question.answers.right_answer
  end

  def next_question
    test.questions.order(:id).where('id > ?', current_question).first
  end

end

test-guru/app/models/user.rb
class User < ApplicationRecord
  define_model_callbacks :deliver
  include MailForm::Delivery
  attributes :name, :email, :message, :created_at

  devise :database_authenticatable,
         :registerable,
         :recoverable,
         :rememberable,
         :validatable,
         :confirmable

  has_many :test_passages, dependent: :destroy
  has_many :tests, through: :test_passages, dependent: :destroy
  has_many :author_tests, class_name: 'Test', foreign_key: :author_id, dependent: :destroy
  has_many :gists, dependent: :destroy
  has_and_belongs_to_many :badges
  before_destroy { badges.clear }

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :login, presence: true,
                    uniqueness: true
  validates :email, presence: true,
                    format: { with: URI::MailTo::EMAIL_REGEXP },
                    uniqueness: true

  def tests_history(level)
    tests.where('level = :level', level: level)
  end

  def test_passage(test)
    test_passages.order(id: :desc).find_by(test_id: test.id)
  end

  def admin?
    is_a?(Admin)
  end
end

test-guru/app/controllers/tests_controller.rb
class TestsController < ApplicationController
  before_action :authenticate_user!, only: %i[start index]
  before_action :find_test, only: %i[show start]
  before_action :user_signed_in?

  def index
    @tests = Test.all
  end

  def start
    current_user.tests.push(@test)
    redirect_to current_user.test_passage(@test)
  end

  private

  def find_test
    @test = Test.find(params[:id])
  end
end

test-guru/app/helpers/application_helper.rb
module ApplicationHelper
end

test-guru/app/helpers/badges_helper.rb
module BadgesHelper
end

test-guru/app/helpers/flash_helper.rb
module FlashHelper
  def flash_header
    if flash[:alert]
      render inline: "<%= content_tag :div, flash[:alert], class: 'alert alert-danger', role:'alert'%><br>"
    elsif flash[:notice]
      render inline: "<%= content_tag :div, flash[:notice], class: 'alert alert-success', role:'alert'%><br>"
    end
  end
end

test-guru/app/helpers/footer_helper.rb
module FooterHelper
  def github_url(author, repo)
    link_to 'TestGuru','https://github.com/' + author.to_s + '/Rails/tree/master/' + repo.to_s,target: '_blank', rel: 'nofollow', class: 'link'
  end

  def current_year
    Time.now.year
  end
end

test-guru/app/helpers/gists_helper.rb
module GistsHelper
end

test-guru/app/helpers/questions_helper.rb
module QuestionsHelper
  def question_header(question)
    if question.persisted?
      render inline: '<h2>Edit <%= @question.test.title %> question</h2><br>'
    else
      render inline: '<h2>Create New <%= @test.title %> question</h2><br>'
    end
  end
end

test-guru/app/helpers/test_passages_helper.rb
module TestPassagesHelper
end

test-guru/app/helpers/tests_helper.rb
module TestsHelper
end

test-guru/app/views/admin/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-admin">
  <%=link_to image_tag("/test_logo.png", height: '100', width: '150'), admin_tests_path, class:"navbar-brand"%>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav font-weight-bolder text-uppercase h5">
      <% if current_user.is_a?(Admin) %>
        <%= octicon "home", height: 24, class: "mt-2" %>  <%=link_to t('nav-home'), admin_tests_path, rel: "nofollow", class:"nav-item nav-link"%>
      <% else %>
        <%= octicon "home", height: 24, class: "mt-2" %>  <%=link_to t('nav-home'), root_path, rel: "nofollow", class:"nav-item nav-link"%>
      <% end %>
    </div>
  </div>
  <span class="navbar-text font-weight-bolder rounded-lg text-white h6">
    <% if user_signed_in? %>
      <%= t('hello', name: current_user.login) %> <%= octicon "sign-out", height: 24, class: 'pl-1' %>
      <%= link_to t('actions.logout'),  destroy_user_session_path, method: :delete, class: 'link text-decoration-none text-white' %>
      <br><%= octicon "verified", height: 24, class: 'pl-1' %> <%= link_to t('actions.badge-progress'), admin_badges_path, class: 'link text-decoration-none text-lowercase text-white' %>
    <% end %><br>
  </span>
</nav>

test-guru/app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>Admin panel | TestGuru</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<%= render 'admin/nav' %>
<div class="wrapper">
  <%=content_tag :div, t('admin-panel'), class: "text-center font-weight-bolder h5 text-white text-uppercase bg-dark" %>
    <div class="container">
      <div class="content">
       <%= flash_header %>
        <%= yield %>
      </div>
    </div>
</div>
<div class="footer">
  <%= render 'shared/footer' %>
</div>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

test-guru/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <title>TestGuru</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag asset_path('favicon.ico') %>
  </head>

  <body>
  <%= render 'shared/nav' %>
    <div class="wrapper">
      <div class="container">
        <div class="content">
           <%= flash_header %>
          <%= yield %>
        </div>
      </div>
  </div>
  <div class="footer">
    <%= render 'shared/footer' %>
  </div>
  <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

test-guru/app/views/shared/_errors.html.erb
<% if resource.present? && resource.errors.any? %>
  <%= content_tag :div, class: "resource-errors", data: {resource_id: resource.id} do %>

  <h4 class="text-danger"><%= t('errors', count: resource.errors.count) %></h4>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <%end %>
    </ul>
  <% end %><br>
<%end %>

test-guru/app/views/shared/_flash.html.erb
<%= flash.each do |key, message| %>
  <%= content_tag :p, flash[:alert], class: "flash #{key}" %><br>
<% end %>

test-guru/app/views/shared/_footer.html.erb
<p style="text-decoration: none"><%= github_url('ImBigman' , 'test-guru')%> - ресурс для создания и прохождения тестов. © <%= current_year %> by Dmitriy Yarikov</p>
<p><%=link_to "Учебный проект в онлайн-школе Thinknetica", "http://thinknetica.com/", target: "_blank", rel: "nofollow", class: "link" %></p>

test-guru/app/views/shared/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-user">
  <%=link_to image_tag("/test_logo.png", height: '100', width: '150'), root_path, class:"navbar-brand"%>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav font-weight-bolder text-uppercase h5">
      <% if user_signed_in? %>
        <% if current_user.admin?%>
          <%= octicon "home", height: 24, class: "mt-2" %> <%=link_to t('nav-home'), admin_tests_path, rel: "nofollow", class:"nav-item nav-link"%>
          <% else %>
          <%= octicon "home", height: 24, class: "mt-2" %> <%=link_to t('nav-home'), root_path, rel: "nofollow", class:"nav-item nav-link"%>
          <% end %>
      <% else %>
        <%= octicon "sign-in", height: 24, class: "mt-2"  %> <%=link_to t('nav-login'),  new_user_session_path, rel: "nofollow", class: "nav-item nav-link" %>
        <%= octicon "person", height: 24, class: "mt-2"  %> <%=link_to t('nav-register'), new_user_registration_path , rel: "nofollow", class: "nav-item nav-link"%>
      <% end %>
      <%= octicon "mail-read", height: 24, class: "mt-2"  %> <%=link_to t('nav-mail'), new_contact_path , rel: "nofollow", class: "nav-item nav-link"%>
    </div>
  </div>
  <span class="navbar-text font-weight-bolder rounded-lg h6">
    <% if user_signed_in? %>
      <%= t('hello', name: current_user.login) %> <%= octicon "sign-out", height: 24, class: 'pl-1' %>
      <%= link_to t('actions.logout'),  destroy_user_session_path, method: :delete, class: 'link text-decoration-none' %>
     <br><%= octicon "verified", height: 24, class: 'pl-1' %> <%= link_to t('actions.badge-progress'), badges_path, class: 'link text-decoration-none text-lowercase text-dark' %>
    <% end %>
  </span>
</nav>