test-guru/config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout }

  get 'sessions/new'
  get 'users/new'
  root to: 'tests#index'

  resources :tests, only: :index do
    resources :questions, shallow: true do
      resources :answers, shallow: true
    end
    member do
      post :start
    end
  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  namespace :admin do
    resources :tests do
      patch :update_inline, on: :member

      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end
    resources :gists
    resources :badges
  end

  resources 'contacts', only: %i[new create]

  resources :badges, only: :index
end

test-guru/app/models/question.rb
class Question < ApplicationRecord
  belongs_to :test
  has_many :answers, dependent: :destroy
  has_many :gists, dependent: :destroy

  validates :body, presence: true
end

test-guru/app/controllers/admin/questions_controller.rb
class Admin::QuestionsController <  Admin::BaseController
  before_action :find_test, only: %i[index new create]
  before_action :find_questions, only: %i[show edit update destroy]

  rescue_from ActiveRecord::RecordNotFound, with: :rescue_with_questions_not_found

  def index; end

  def show; end

  def edit; end

  def new
    @question = Question.new
  end

  def create
    @question = @test.questions.new(question_params)
    if @question.save
      redirect_to admin_test_path(@question.test)
    else
      render :new
    end
  end

  def update
    if @question.update(question_params)
      redirect_to admin_test_path(@question.test)
    else
      render :edit
    end
  end

  def destroy
    @question.destroy
    redirect_to admin_test_path(@question.test)
  end

  private

  def find_test
    @test = Test.find(params[:test_id])
  end

  def find_questions
    @question = Question.find(params[:id])
  end

  def question_params
    params.require(:question).permit(:body)
  end

  def rescue_with_questions_not_found
    render plain: 'Question was not found!'
  end
end

test-guru/app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_user!

  rescue_from ActiveRecord::RecordNotFound, with: :rescue_with_questions_not_found

  private

  def rescue_with_questions_not_found
    render plain: 'Question was not found!'
  end
end

test-guru/app/helpers/questions_helper.rb
module QuestionsHelper
  def question_header(question)
    if question.persisted?
      render inline: '<h2>Edit <%= @question.test.title %> question</h2><br>'
    else
      render inline: '<h2>Create New <%= @test.title %> question</h2><br>'
    end
  end
end

test-guru/app/views/admin/questions/_form.html.erb
<%= question_header(@question) %>
<%= form_with model: [:admin, @test, @question], local:true do |form|  %>
<%= render 'shared/errors', resource: @question %>
  <p>
    <%= form.label :body %><br>
    <%= form.text_field :body %>
  </p>
  <%= form.submit class:'btn btn-outline-secondary'  %>
<% end %>
<%= content_tag :p %>

test-guru/app/views/admin/questions/edit.html.erb
<%= render 'form' %>
<%= link_to 'Back', admin_test_path(@question.test), class: 'btn btn-outline-secondary mt-3' %>

test-guru/app/views/admin/questions/index.html.erb
<table>
  <tr>
    <th>Question</th>
  </tr>
  <tr>
     <td><% @test.questions.each do |question| %>
        <p> <%= question.body  %> <%= link_to 'Edit', edit_admin_question_path(question) %>
      <% end %></td>
  </tr>
</table>
<%= link_to t('actions.back'), admin_tests_path(@test), class:'btn btn-outline-secondary' %>

test-guru/app/views/admin/questions/new.html.erb
<%= render 'form' %>
<%= link_to 'Back', admin_test_path(@test), class:'btn btn-outline-secondary' %>

test-guru/app/views/admin/questions/show.html.erb
<h2><%= @question.test.title %> question </h2><br>
<p class="h4">Что вы можете рассказать о <%= @question.body %> ?</p>
<table>
  <tr class="h6">
    <td><strong>Test's title: </strong><%= @question.test.title  %></td>
    <td><strong>Question: </strong><%= @question.body %></td>
  </tr>
</table>
<h3>Answers</h3>
<%= link_to 'New answer', new_admin_question_answer_path(@question) %>
<ol>
  <%= render @question.answers %>
</ol><br>

<%= link_to t('actions.back'), admin_test_path(@question.test), class: 'btn btn-outline-secondary' %>