test-guru/config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout }

  get 'sessions/new'
  get 'users/new'
  root to: 'tests#index'

  resources :tests, only: :index do
    resources :questions, shallow: true do
      resources :answers, shallow: true
    end
    member do
      post :start
    end
  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  namespace :admin do
    resources :tests do
      patch :update_inline, on: :member

      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end
    resources :gists
    resources :badges
  end

  resources 'contacts', only: %i[new create]

  resources :badges, only: :index
end

test-guru/app/models/question.rb
class Question < ApplicationRecord
  belongs_to :test
  has_many :answers, dependent: :destroy
  has_many :gists, dependent: :destroy

  validates :body, presence: true
end

test-guru/app/models/test_passage.rb
class TestPassage < ApplicationRecord
  belongs_to :user
  belongs_to :test
  belongs_to :current_question, class_name: 'Question', optional: true
  has_and_belongs_to_many :badges
  before_destroy { badges.clear }

  before_validation :before_validation_set_first_question, on: :create

  BOUNDARY_OF_SUCCESS = 85

  before_update do
    self.current_question = next_question
  end

  def accept!(answer_ids)
    self.correct_questions += 1 if correct_answer?(answer_ids)
    save!
  end

  def completed?
    current_question.nil?
  end

  def success?
    percentage_result < BOUNDARY_OF_SUCCESS
  end

  def percentage_result
    a = test.questions.count
    b = correct_questions
    (Float(b * 100) / a).ceil
  end

  def current_question_number
    test.questions.to_a.index(current_question) + 1
  end

  def all_questions
    test.questions.count
  end

  def progress
    Float(((current_question_number - 1) * 100) / all_questions).ceil
  end

  def end_time
    (created_at + (test.timer * 60)).to_s(:js_datetime)
  end

  def check_timer
    end_time < Time.now.to_s(:js_datetime)
  end

  private

  def before_validation_set_first_question
    self.current_question = test.questions.first if test.present?
  end

  def correct_answer?(answer_ids)
    return if answer_ids.nil?

    correct_answers.ids.sort == answer_ids.map(&:to_i).sort
  end

  def correct_answers
    current_question.answers.right_answer
  end

  def next_question
    test.questions.order(:id).where('id > ?', current_question).first
  end

end

test-guru/app/controllers/test_passages_controller.rb
class TestPassagesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_test_passage, only: %i[show result update gist progress]

  def show; end

  def result
    @test_passage.success? ? @test_passage.update(completed: false) : @test_passage.update(completed: true)
    return unless @test_passage.completed == true

    award = BadgeService.new(@test_passage)
    award.call
  end

  def update
    overtime
    @test_passage.accept!(params[:answer_ids])
    if @test_passage.completed?
      TestsMailer.completed_test(@test_passage).deliver_now
      redirect_to result_test_passage_path(@test_passage)
    else
      render :show
    end
  end

  def gist
    connection = GistQuestionService.new(@test_passage.current_question)
    result = connection.call

    if connection.success?
      current_user.gists.create(question_id: @test_passage.current_question.id, url: result.html_url)
      flash_options = { notice: t('.success') + " Gist: #{result.html_url}" }
    else
      flash_options = { alert: t('.failure') }
    end

    redirect_to @test_passage, flash_options
  end

  def overtime
    return unless @test_passage.check_timer

    redirect_to(result_test_passage_path(@test_passage)) && (return)
  end

  private

  def set_test_passage
    @test_passage = TestPassage.find(params[:id])
  end
end

test-guru/app/helpers/test_passages_helper.rb
module TestPassagesHelper
end

test-guru/app/views/test_passages/_badges.html.erb
<tr>
  <% @test_passage.badges.each do |badge| %>
    <td class="mid_align"><%= render inline: badge.url %>- </td>
    <td class="mid_align"><%= badge.name %></td><br>
  <%end %>
</tr>

test-guru/app/views/test_passages/_test_passage.html.erb
<tr>
  <td class="mid_align"><%= test_passage.test.title %></td>
  <td class="mid_align"><%= test_passage.test.category.title %></td>
  <td class="mid_align"><%= test_passage.updated_at %></td>
</tr>

test-guru/app/views/test_passages/result.html.erb
<h2><%= t('.header', test: @test_passage.test.title) %> </h2>
<%= content_tag :h5,t('test_passages.show.counter-end', current_question: @test_passage.all_questions, all_questions: @test_passage.all_questions), id:'progress-bar-title'%>
<%=t('test_passages.show.progress-bar') %>
<div class="progress" style="height: 40px;">
  <div class="progress-bar bg-warning font-weight-bolder text-body" role="progressbar" style="width: 100%" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100">100%</div>
  </div>
<% if @test_passage.badges.exists? %>
  <br><%= content_tag :p, t('test_passages.show.achive-header') %>
  <%=render 'badges' %>
<% end %>
<br> <h3><%= t('.message', user: current_user.login, count: @test_passage.correct_questions) %> </h3>
<br>
<% if @test_passage.success?%>
  <h3 style='color: #b70000;'><%= t('.fail', result:@test_passage.percentage_result)%> </h3>
  <% else %>
  <h3 style='color: green;'><%= t('.success', result:@test_passage.percentage_result)%></h3>
 <% end %><br>
<%= link_to t('.back to tests'), tests_path, class: 'button' %>

test-guru/app/views/test_passages/show.html.erb
<h2><%= t('.header',title: @test_passage.test.title) %></h2>
<%= content_tag :h5,t('.counter', current_question: @test_passage.current_question_number, all_questions: @test_passage.all_questions), id: 'progress', data: {test_progress: @test_passage.progress.to_s + '%' }%>
<div class="row border rounded">
  <div class="col-md-4 content">
    <%=content_tag :h5, t('.progress-timer'), id: 'timer-label', style: 'color: #846540', class: 'font-weight-bold mt-3', data: { progress_timer: @test_passage.end_time } %>
  </div>
  <div class="col-md-8 content d-flex justify-content-end">
    <div id="clockdiv">
      <div>
        <span class="minutes"></span>
      </div>
      <div>
        <span class="seconds"></span>
      </div>
    </div>
  </div>
</div>
<h5 class="hidden-message text-danger text-center font-weight-normal hide"> <%=t('.endtime') %> </h5>
<%=t('.progress-bar') %>
<div class="progress" style="height: 40px;">
  <div class="progress-bar bg-warning font-weight-bolder text-body" role="progressbar" style="width: 0" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100"><%= @test_passage.progress%>%</div>
</div>
<h3>
  <%= t('.title', title: @test_passage.current_question.body) %>
</h3>
<%= form_with url: test_passage_path(@test_passage), local: true, method: :put do |form| %>
  <%= form.collection_check_boxes :answer_ids,  @test_passage.current_question.answers, :id, :body, include_hidden: false  do |a|%>
    <p style="padding: 10px">
      <%= a.check_box id: "answer_ids_#{a.object.id}"%>
      <%= a.label %>
    </p>
  <% end %><br>
  <div class="row">
  <div class="col-md-6 content  d-flex justify-content-start">
    <span class="next-question"><%= form.submit t('.next'), class:'btn btn-outline-secondary'  %></span>
  </div>
   <div class="col-md-6 content  d-flex justify-content-end">
     <%= link_to t('.gist link'), gist_test_passage_path(@test_passage), method: :post, class:'btn btn-outline-info' %>
   </div>
  </div>
<% end %>